<?php
// SESMT GERAL: definição dos cadastros e das listas iniciais, convertidos da planilha "Gestão SST - Rótula".
// Cada cadastro vira uma tabela sesmt_<chave>. A tela, a validação e o esquema são gerados daqui.
// As listas abaixo são as "fontes de dados" das caixas de seleção da planilha. A lista de nomes de colaboradores
// NÃO foi trazida: os colaboradores são cadastrados no sistema, cada um com a sua empresa.

/** Atalho para declarar um campo. Opções: r=obrigatório, l=aparece na lista, q=entra na busca, pad=valor padrão, dica, full. */
function sesmt_campo($rotulo, $tipo = 'txt', array $opcoes = [])
{
    return array_merge(['rotulo' => $rotulo, 'tipo' => $tipo], $opcoes);
}

function sesmt_listas_iniciais()
{
    $mov = ['Primeira entrega, admissão', 'Substituição por dano justificado', 'Substituição por dano próprio ou perda',
        'Troca do EPI, danificado ou vencido', 'Devolução, demissão ou mudança de função'];
    return [
        'status_colaborador' => ['Status do colaborador', ['Contratado', 'Experiência', 'Jovem aprendiz', 'Demitido', 'Autônomo', 'Estágio', 'PJ']],
        'sexo' => ['Sexo', ['M', 'F']],
        'setor' => ['Setores', ['Operacional', 'Administrativo', 'Projetos', 'SMS', 'Financeiro']],
        'funcao' => ['Funções', ['Ajudante Geral', 'Ajudante Prático', 'Arquiteto(a)', 'Aux. Administrativo', 'Projetista', 'Eletricista II',
            'Eletricista I', 'Serviços Gerais', 'Encarregado', 'Cabo de Turma', 'Engenheiro Civil', 'Engenheiro Eletricista',
            'Engenheiro de Segurança', 'Estagiário(a)', 'Analista Financeiro', 'Motorista B e D', 'Pedreiro I', 'Serralheiro',
            'Supervisor', 'Téc. Eletrotécnico', 'Téc. De Segurança']],
        'sn' => ['Sim / Não', ['Sim', 'Não']],
        'apto' => ['Apto / Não apto', ['Apto', 'Não apto']],
        'aso_tipo' => ['Tipo de ASO', ['Periódico', 'Admissional', 'Retorno ao trabalho', 'Mudança de função', 'Demissional']],
        'aso_validade' => ['Prazos de validade do ASO (dias)', ['90', '135']],
        'acidente_status' => ['Status do acidente', ['Concluído', 'Aguardando ação', 'Investigação']],
        'acidente_tipo' => ['Tipo de acidente', ['Típico', 'Trajeto', 'Doença']],
        'dano_lesao' => ['Dano / lesão', ['Queimadura', 'Fratura', 'Queda', 'Objeto estranho', 'Corte', 'Escoriação', 'Torção']],
        'parte_corpo' => ['Parte do corpo atingida', ['Cabeça', 'Olhos', 'Nariz', 'Pescoço', 'Face', 'Braço', 'Mão', 'Dedo', 'Abdômen', 'Perna', 'Joelho', 'Pé']],
        'agente_causador' => ['Agente causador', ['Piso', 'Andaime', 'Escada', 'Rampa', 'Serra', 'Choque elétrico', 'Produto químico']],
        'nivel_acidente' => ['Pirâmide de Bird (nível do acidente)', ['Fatalidade (acidente com morte)', 'Acidentes com lesões graves', 'Acidentes com lesões leves']],
        'treinamento_status' => ['Status do treinamento', ['Concluído', 'Em andamento', 'Agendado', 'Cancelado']],
        'norma' => ['Normas regulamentadoras', ['NR 06', 'NR 10', 'NR 12', 'NR 13', 'NR 18', 'NR 20', 'NR 33', 'NR 35']],
        'finalidade' => ['Finalidade do treinamento', ['Admissional', 'Periódico', 'Eventual']],
        'modalidade' => ['Modalidade do treinamento', ['Presencial', 'EAD', 'Semipresencial']],
        'auditoria_tipo' => ['Tipo de auditoria', ['Interna', 'Externa']],
        'auditoria_status' => ['Status (auditoria e DDS)', ['Realizada', 'Em aberto', 'Agendada', 'Cancelada']],
        'desvio_ocorrencia' => ['Desvio ou incidente', ['Incidente', 'Desvio']],
        'desvio_tipo' => ['Tipo do desvio / incidente', ['EPI', 'Ferramenta', 'Máquinas', 'Treinamentos', 'Comportamental', 'Ambiente']],
        'desvio_gravidade' => ['Gravidade do desvio', ['Baixa', 'Média', 'Alta']],
        'plano_status' => ['Status do plano 5W2H', ['REALIZADO', 'EM ABERTO', 'AGENDADO', 'CANCELADO']],
        'plano_prioridade' => ['Prioridade do plano 5W2H', ['URGENTE', 'ALTA', 'MÉDIA', 'BAIXA']],
        'risco_tipo' => ['Tipos de risco', ['ACIDENTE', 'QUÍMICO', 'FÍSICO', 'BIOLÓGICO', 'ERGONÔMICO']],
        'probabilidade' => ['Probabilidade (1 a 5)', ['REMOTA', 'BAIXA', 'MÉDIA', 'ALTA', 'MUITO ALTA'], true],
        'severidade' => ['Severidade (1 a 5)', ['SEM IMPACTO', 'LEVE', 'MÉDIO', 'GRAVE', 'GRAVÍSSIMO'], true],
        'manut_status' => ['Status da manutenção', ['Realizada', 'Não realizada', 'Agendada']],
        'manut_tipo' => ['Tipo de manutenção', ['Corretiva', 'Preventiva', 'Preditiva']],
        'manut_prioridade' => ['Prioridade da manutenção', ['Altíssima', 'Alta', 'Média', 'Baixa']],
        'epi_movimento' => ['Entrada ou saída de EPI', ['ENTRADA', 'SAÍDA'], true],
        'epi_parte' => ['Funcionário ou fornecedor', ['Funcionário', 'Fornecedor'], true],
        'epi_motivo' => ['Motivos de entrega e devolução (MED)', $mov],
        'extintor_tipo' => ['Tipos de extintor', ['PQS ABC-6KG', 'PQS BC-12KG', 'PQS BC-6KG', 'AP-10L', 'CO2-12KG']],
        'cipa_eleito' => ['Condição na CIPA', ['TITULAR', 'SUPLENTE'], true],
        'tipo_veiculo' => ['Tipos de veículo', ['Carro', 'Motocicleta', 'Caminhão', 'Ônibus', 'Micro-ônibus', 'Reboque', 'Utilitário', 'Outro']],
        'frota_manut_tipo' => ['Tipos de manutenção da frota', ['Preditiva', 'Preventiva', 'Corretiva']],
        'quimico_perigo' => ['Representa perigo?', ['SIM', 'NÃO', 'NÃO APLICÁVEL']],
    ];
}

function sesmt_texto_oss_padrao()
{
    return "Dar ciência aos empregados, com o seguinte intuito:\nI - Prevenir atos inseguros no desempenho do trabalho;\n"
        . "II - Divulgar as obrigações e proibições que os empregados devam conhecer e cumprir;\n"
        . "III - Dar conhecimento aos empregados de que serão passíveis de punição, pelo descumprimento das ordens de serviço expedidas.";
}

/** Matriz de risco 5x5 da planilha: valor = probabilidade x severidade. */
function sesmt_faixas_risco()
{
    return [[1, 3, 'TRIVIAL', 'verde'], [4, 8, 'BAIXO', 'verde'], [9, 14, 'MODERADO', 'amarelo'], [15, 19, 'ALTO', 'vermelho'], [20, 25, 'EXTREMO', 'vermelho']];
}

/** Cadastros do SESMT. Grupos organizam o menu. emp: obrig | opc | colab | nenhum (como a empresa é identificada). */
function sesmt_registros()
{
    static $r = null;
    if ($r !== null) {
        return $r;
    }
    $f = 'sesmt_campo';
    $r = [
        'colaboradores' => [
            'grupo' => 'Pessoas', 'titulo' => 'Colaboradores', 'singular' => 'colaborador', 'emp' => 'obrig', 'ordem' => 'nome',
            'ajuda' => 'Cadastro dos colaboradores de cada empresa. A coluna Empresa identifica a quem cada colaborador pertence.',
            'campos' => [
                'empresa' => $f('Empresa', 'empresa', ['r' => 1, 'l' => 1, 'q' => 1]),
                'status' => $f('Status', 'lista:status_colaborador', ['r' => 1, 'l' => 1, 'pad' => 'Contratado']),
                'nome' => $f('Nome do colaborador', 'txt', ['r' => 1, 'l' => 1, 'q' => 1]),
                'cpf' => $f('CPF', 'cpf', ['l' => 1, 'q' => 1]),
                'rg' => $f('RG'),
                'setor' => $f('Setor', 'lista:setor', ['l' => 1, 'q' => 1]),
                'funcao' => $f('Função', 'lista:funcao', ['l' => 1, 'q' => 1]),
                'sexo' => $f('Sexo', 'lista:sexo'),
                'nascimento' => $f('Nascimento', 'data'),
                'admissao' => $f('Data de admissão', 'data', ['l' => 1]),
                'desligamento' => $f('Data do desligamento', 'data'),
                'ctps' => $f('CTPS'),
                'serie' => $f('Série'),
                'endereco' => $f('Endereço', 'txt', ['full' => 1]),
                'celular' => $f('Celular'),
                'obs' => $f('Observações', 'longo', ['full' => 1]),
            ],
            'calc' => ['idade' => 'Idade', 'tempo' => 'Tempo de empresa'],
        ],
        'aso' => [
            'grupo' => 'Pessoas', 'titulo' => 'ASO', 'singular' => 'ASO', 'emp' => 'colab', 'ordem' => 'data_emissao DESC',
            'ajuda' => 'Atestado de Saúde Ocupacional. O vencimento e a situação são calculados pela emissão e pela validade em dias.',
            'campos' => [
                'colaborador_id' => $f('Colaborador', 'ref:colaboradores', ['r' => 1, 'l' => 1]),
                'tipo' => $f('Tipo', 'lista:aso_tipo', ['r' => 1, 'l' => 1]),
                'data_emissao' => $f('Data da emissão', 'data', ['r' => 1, 'l' => 1]),
                'validade_dias' => $f('Validade (em dias)', 'int:aso_validade', ['r' => 1, 'dica' => 'Digite ou escolha um prazo da lista.']),
                'apto' => $f('Apto / não apto', 'lista:apto', ['l' => 1]),
                'medico' => $f('Médico', 'txt', ['q' => 1]),
                'crm' => $f('CRM'),
                'atualizou' => $f('Já atualizou o ASO?', 'lista:sn', ['pad' => 'Não', 'dica' => 'Marque Sim quando existir um ASO mais novo para o colaborador.']),
                'exames' => $f('Exames realizados', 'longo', ['full' => 1]),
            ],
            'calc' => ['vencimento' => 'Vencimento', 'situacao' => 'Situação'],
        ],
        'treinamentos' => [
            'grupo' => 'Pessoas', 'titulo' => 'Treinamentos', 'singular' => 'treinamento', 'emp' => 'opc', 'ordem' => 'data_final DESC',
            'ajuda' => 'Treinamentos realizados ou agendados. A validade conta a partir da data final.',
            'campos' => [
                'empresa' => $f('Empresa', 'empresa', ['l' => 1, 'dica' => 'Opcional. Preencha quando o treinamento for de uma empresa específica.']),
                'status' => $f('Status', 'lista:treinamento_status', ['r' => 1, 'l' => 1]),
                'treinamento' => $f('Treinamento', 'txt', ['r' => 1, 'l' => 1, 'q' => 1]),
                'norma' => $f('Norma', 'lista:norma', ['l' => 1]),
                'data_inicial' => $f('Data inicial', 'data'),
                'data_final' => $f('Data final', 'data', ['l' => 1]),
                'validade_meses' => $f('Validade (em meses)', 'int'),
                'controlar' => $f('Controlar validade?', 'lista:sn', ['pad' => 'Sim']),
                'instrutor' => $f('Instrutor', 'txt', ['q' => 1]),
                'horas' => $f('Duração (em horas)', 'num'),
                'finalidade' => $f('Finalidade', 'lista:finalidade'),
                'modalidade' => $f('Modalidade', 'lista:modalidade'),
                'local' => $f('Local'),
                'custo' => $f('Custo (R$)', 'num'),
            ],
            'calc' => ['alunos' => 'Participantes', 'vencimento' => 'Vencimento', 'situacao' => 'Validade'],
        ],
        'presenca' => [
            'grupo' => 'Pessoas', 'titulo' => 'Lista de presença', 'singular' => 'presença', 'emp' => 'colab', 'ordem' => 'id DESC',
            'ajuda' => 'Quem participou de cada treinamento. Escolha o treinamento e marque vários colaboradores de uma vez.',
            'campos' => [
                'treinamento_id' => $f('Treinamento', 'ref:treinamentos', ['r' => 1, 'l' => 1]),
                'colaborador_id' => $f('Colaborador', 'ref:colaboradores', ['r' => 1, 'l' => 1]),
                'obs' => $f('Observações', 'txt', ['full' => 1]),
            ],
            'calc' => ['norma' => 'Norma', 'conclusao' => 'Conclusão', 'vencimento' => 'Vencimento', 'situacao' => 'Validade'],
        ],
        'advertencias' => [
            'grupo' => 'Pessoas', 'titulo' => 'Advertências', 'singular' => 'advertência', 'emp' => 'colab', 'ordem' => 'data DESC',
            'ajuda' => 'Registro de advertências. Setor e função vêm do cadastro do colaborador.',
            'campos' => [
                'colaborador_id' => $f('Colaborador', 'ref:colaboradores', ['r' => 1, 'l' => 1]),
                'data' => $f('Data', 'data', ['r' => 1, 'l' => 1]),
                'hora' => $f('Hora', 'hora'),
                'ato' => $f('Ato faltoso', 'longo', ['r' => 1, 'l' => 1, 'q' => 1, 'full' => 1]),
            ],
            'calc' => ['setor' => 'Setor', 'funcao' => 'Função'],
        ],
        'cipa' => [
            'grupo' => 'Pessoas', 'titulo' => 'CIPA e estabilidade', 'singular' => 'cipeiro', 'emp' => 'colab', 'ordem' => 'data_posse DESC',
            'ajuda' => 'Membros da CIPA. O mandato dura 1 ano e a estabilidade vai até 2 anos após a posse, como na planilha.',
            'campos' => [
                'gestao' => $f('Gestão da CIPA', 'txt', ['r' => 1, 'l' => 1, 'dica' => 'Exemplo: 2026-2027']),
                'colaborador_id' => $f('Cipeiro', 'ref:colaboradores', ['r' => 1, 'l' => 1]),
                'data_posse' => $f('Data da posse', 'data', ['r' => 1, 'l' => 1]),
                'eleito' => $f('Condição', 'lista:cipa_eleito', ['l' => 1]),
                'votos' => $f('Nº de votos', 'int'),
                'controlar' => $f('Controlar status?', 'lista:sn', ['pad' => 'Sim']),
            ],
            'calc' => ['fim_mandato' => 'Final do mandato', 'situacao' => 'Mandato', 'fim_estab' => 'Final da estabilidade', 'situacao2' => 'Estabilidade'],
        ],
        'acidentes' => [
            'grupo' => 'Ocorrências', 'titulo' => 'Acidentes', 'singular' => 'acidente', 'emp' => 'colab', 'ordem' => 'data DESC',
            'ajuda' => 'Registro de acidentes de trabalho. Alimenta os dias sem acidente e as taxas do painel.',
            'campos' => [
                'colaborador_id' => $f('Colaborador', 'ref:colaboradores', ['r' => 1, 'l' => 1]),
                'data' => $f('Data', 'data', ['r' => 1, 'l' => 1]),
                'horario' => $f('Horário', 'hora', ['l' => 1]),
                'status' => $f('Status', 'lista:acidente_status', ['l' => 1]),
                'tipo' => $f('Tipo', 'lista:acidente_tipo', ['l' => 1]),
                'dano' => $f('Dano / lesão', 'lista:dano_lesao'),
                'parte' => $f('Parte do corpo atingida', 'lista:parte_corpo'),
                'agente' => $f('Agente causador', 'lista:agente_causador'),
                'local' => $f('Local do acidente', 'txt', ['q' => 1]),
                'cat' => $f('Emitir CAT?', 'lista:sn'),
                'gravidade' => $f('Gravidade (Pirâmide de Bird)', 'lista:nivel_acidente', ['l' => 1]),
                'afastamento' => $f('Afastamento', 'lista:sn', ['l' => 1]),
                'data_retorno' => $f('Data de retorno', 'data'),
                'detalhes' => $f('Detalhes', 'longo', ['full' => 1, 'q' => 1]),
            ],
            'calc' => ['dias' => 'Dias perdidos'],
        ],
        'desvios' => [
            'grupo' => 'Ocorrências', 'titulo' => 'Desvios e incidentes', 'singular' => 'desvio', 'emp' => 'opc', 'ordem' => 'data DESC',
            'ajuda' => 'Desvios e incidentes com ação corretiva. A situação da ação depende do prazo e da data de conclusão.',
            'campos' => [
                'empresa' => $f('Empresa', 'empresa', ['l' => 1]),
                'ocorrencia' => $f('Desvio ou incidente', 'lista:desvio_ocorrencia', ['r' => 1, 'l' => 1]),
                'descricao' => $f('Descrição', 'longo', ['r' => 1, 'l' => 1, 'q' => 1, 'full' => 1]),
                'data' => $f('Data', 'data', ['r' => 1, 'l' => 1]),
                'tipo' => $f('Tipo', 'lista:desvio_tipo', ['l' => 1]),
                'gravidade' => $f('Gravidade', 'lista:desvio_gravidade', ['l' => 1]),
                'setor' => $f('Setor', 'lista:setor'),
                'acoes' => $f('Ações a serem realizadas', 'longo', ['full' => 1]),
                'prazo' => $f('Prazo para conclusão', 'data', ['l' => 1]),
                'conclusao' => $f('Data da conclusão', 'data'),
            ],
            'calc' => ['situacao' => 'Situação da ação'],
        ],
        'auditorias' => [
            'grupo' => 'Ocorrências', 'titulo' => 'Auditorias', 'singular' => 'auditoria', 'emp' => 'opc', 'ordem' => 'data DESC',
            'ajuda' => 'Auditorias internas e externas e as não conformidades encontradas e resolvidas.',
            'campos' => [
                'empresa' => $f('Empresa', 'empresa', ['l' => 1]),
                'auditoria' => $f('Auditoria', 'txt', ['r' => 1, 'l' => 1, 'q' => 1]),
                'tipo' => $f('Tipo da auditoria', 'lista:auditoria_tipo', ['l' => 1]),
                'data' => $f('Data', 'data', ['l' => 1]),
                'status' => $f('Status', 'lista:auditoria_status', ['l' => 1]),
                'normas' => $f('Normas'),
                'nc_encontradas' => $f('Não conformidades encontradas', 'int', ['l' => 1]),
                'nc_resolvidas' => $f('Não conformidades resolvidas', 'int', ['l' => 1]),
            ],
            'calc' => ['percentual' => '% resolvido'],
        ],
        'planos' => [
            'grupo' => 'Ocorrências', 'titulo' => 'Planos 5W2H', 'singular' => 'plano', 'emp' => 'opc', 'ordem' => 'conclusao',
            'ajuda' => 'Planos de ação no formato 5W2H: o quê, quem, onde, por quê, como, quanto e quando.',
            'campos' => [
                'empresa' => $f('Empresa', 'empresa', ['l' => 1]),
                'nome' => $f('Nome do plano', 'txt', ['r' => 1, 'l' => 1, 'q' => 1]),
                'status' => $f('Status', 'lista:plano_status', ['r' => 1, 'l' => 1, 'pad' => 'EM ABERTO']),
                'prioridade' => $f('Prioridade', 'lista:plano_prioridade', ['l' => 1]),
                'data' => $f('Data', 'data'),
                'o_que' => $f('O quê?', 'longo', ['full' => 1]),
                'quem' => $f('Quem?', 'txt', ['l' => 1, 'q' => 1]),
                'onde' => $f('Onde?'),
                'por_que' => $f('Por quê?', 'longo', ['full' => 1]),
                'como' => $f('Como?', 'longo', ['full' => 1]),
                'quanto' => $f('Quanto? (R$)', 'num'),
                'conclusao' => $f('Conclusão prevista', 'data', ['l' => 1]),
                'obs' => $f('Observações', 'longo', ['full' => 1]),
            ],
            'calc' => ['situacao' => 'Prazo'],
        ],
        'dds' => [
            'grupo' => 'Ocorrências', 'titulo' => 'DDS', 'singular' => 'DDS', 'emp' => 'opc', 'ordem' => 'data DESC',
            'ajuda' => 'Diálogo diário de segurança.',
            'campos' => [
                'empresa' => $f('Empresa', 'empresa', ['l' => 1]),
                'status' => $f('Status do DDS', 'lista:auditoria_status', ['l' => 1]),
                'descricao' => $f('Descrição do DDS', 'longo', ['r' => 1, 'l' => 1, 'q' => 1, 'full' => 1]),
                'data' => $f('Data', 'data', ['r' => 1, 'l' => 1]),
                'departamento' => $f('Departamento', 'txt', ['l' => 1]),
                'instrutor' => $f('Instrutor', 'txt', ['q' => 1]),
            ],
            'calc' => [],
        ],
        'epi' => [
            'grupo' => 'EPI e riscos', 'titulo' => 'Cadastro de EPI', 'singular' => 'EPI', 'emp' => 'nenhum', 'ordem' => 'descricao',
            'ajuda' => 'Catálogo de EPIs. Entradas, saídas e estoque vêm das movimentações.',
            'campos' => [
                'descricao' => $f('Descrição do EPI', 'txt', ['r' => 1, 'l' => 1, 'q' => 1]),
                'fabricante' => $f('Fabricante', 'txt', ['l' => 1]),
                'ca' => $f('Número do CA', 'txt', ['l' => 1, 'q' => 1]),
                'vencimento' => $f('Data de vencimento', 'data'),
                'minimo' => $f('Estoque mínimo', 'num', ['r' => 1]),
                'maximo' => $f('Estoque máximo', 'num', ['r' => 1]),
                'preco' => $f('Preço unitário (R$)', 'num'),
                'controlar' => $f('Controlar validade?', 'lista:sn', ['pad' => 'Sim']),
            ],
            'calc' => ['entradas' => 'Entradas', 'saidas' => 'Saídas', 'estoque' => 'Estoque atual', 'situacao_estoque' => 'Situação do estoque', 'valor' => 'Valor em estoque', 'situacao' => 'Validade'],
        ],
        'mov_epi' => [
            'grupo' => 'EPI e riscos', 'titulo' => 'Movimentação de EPI', 'singular' => 'movimentação', 'emp' => 'colab', 'ordem' => 'data DESC, id DESC',
            'ajuda' => 'Entradas no estoque e entregas aos colaboradores. A saída não pode passar do estoque disponível.',
            'campos' => [
                'epi_id' => $f('EPI', 'ref:epi', ['r' => 1, 'l' => 1]),
                'movimento' => $f('Entrada ou saída', 'lista:epi_movimento', ['r' => 1, 'l' => 1]),
                'qtd' => $f('Quantidade', 'num', ['r' => 1, 'l' => 1]),
                'parte' => $f('Funcionário ou fornecedor', 'lista:epi_parte', ['r' => 1]),
                'colaborador_id' => $f('Colaborador', 'ref:colaboradores', ['l' => 1, 'dica' => 'Obrigatório quando for funcionário.']),
                'fornecedor' => $f('Fornecedor', 'txt', ['l' => 1, 'q' => 1]),
                'data' => $f('Data', 'data', ['r' => 1, 'l' => 1]),
                'devolucao' => $f('Data de devolução', 'data'),
                'motivo' => $f('Motivo da entrega ou devolução (MED)', 'lista:epi_motivo', ['full' => 1]),
                'ficha' => $f('ID da ficha de EPI'),
            ],
            'calc' => ['ca' => 'CA', 'total' => 'Preço total'],
        ],
        'riscos' => [
            'grupo' => 'EPI e riscos', 'titulo' => 'Riscos ambientais', 'singular' => 'risco', 'emp' => 'nenhum', 'ordem' => 'id DESC',
            'ajuda' => 'Inventário de riscos por função e setor. A classificação sai da matriz 5x5: probabilidade vezes severidade.',
            'campos' => [
                'funcao' => $f('Função', 'lista:funcao', ['r' => 1, 'l' => 1, 'q' => 1]),
                'setor' => $f('Setor', 'lista:setor', ['l' => 1]),
                'tipo' => $f('Tipo do risco', 'lista:risco_tipo', ['l' => 1]),
                'descricao' => $f('Descrição do risco', 'longo', ['r' => 1, 'l' => 1, 'q' => 1, 'full' => 1]),
                'danos' => $f('Danos ou lesões'),
                'expostos' => $f('Quantidade de expostos', 'int'),
                'exposicao' => $f('Tempo ou tipo da exposição'),
                'controles' => $f('Controles existentes', 'longo', ['full' => 1]),
                'probabilidade' => $f('Probabilidade', 'lista:probabilidade', ['r' => 1]),
                'severidade' => $f('Severidade', 'lista:severidade', ['r' => 1]),
            ],
            'calc' => ['valor' => 'Pontos', 'classe' => 'Classificação de risco'],
        ],
        'atividades' => [
            'grupo' => 'EPI e riscos', 'titulo' => 'Atividades por função', 'singular' => 'atividade', 'emp' => 'nenhum', 'ordem' => 'funcao',
            'ajuda' => 'Descrição das atividades, riscos, EPIs e medidas preventivas de cada função. Base das ordens de serviço.',
            'campos' => [
                'funcao' => $f('Função', 'lista:funcao', ['r' => 1, 'l' => 1, 'q' => 1]),
                'setor' => $f('Setor', 'lista:setor', ['l' => 1]),
                'descricao' => $f('Descrição das atividades desenvolvidas', 'longo', ['full' => 1, 'l' => 1, 'q' => 1]),
                'riscos' => $f('Riscos das atividades desenvolvidas', 'longo', ['full' => 1]),
                'epis' => $f('Equipamentos de proteção individual', 'longo', ['full' => 1]),
                'medidas' => $f('Medidas preventivas', 'longo', ['full' => 1]),
                'obrigacoes' => $f('Obrigações', 'longo', ['full' => 1]),
                'sancoes' => $f('Sanções', 'longo', ['full' => 1]),
                'procedimentos' => $f('Procedimentos em caso de acidente', 'longo', ['full' => 1]),
                'normas' => $f('Normas internas', 'longo', ['full' => 1]),
                'obs' => $f('Observações', 'longo', ['full' => 1]),
                'termo' => $f('Termo de responsabilidade', 'longo', ['full' => 1]),
            ],
            'calc' => [],
        ],
        'oss' => [
            'grupo' => 'EPI e riscos', 'titulo' => 'Ordens de serviço (OSS)', 'singular' => 'OSS', 'emp' => 'colab', 'ordem' => 'id DESC',
            'ajuda' => 'Ordem de Serviço de Segurança, por função ou individual (escolha o colaborador).',
            'campos' => [
                'numero' => $f('Número da OSS', 'txt', ['r' => 1, 'l' => 1, 'q' => 1]),
                'funcao' => $f('Função', 'lista:funcao', ['l' => 1]),
                'colaborador_id' => $f('Colaborador (OSS individual)', 'ref:colaboradores', ['l' => 1]),
                'elaboracao' => $f('Data da elaboração', 'data', ['l' => 1]),
                'revisao' => $f('Data da revisão', 'data'),
                'objetivo' => $f('Objetivo', 'longo', ['full' => 1, 'pad' => sesmt_texto_oss_padrao()]),
                'atividades' => $f('Descrição das atividades desenvolvidas', 'longo', ['full' => 1]),
                'riscos' => $f('Riscos das atividades desenvolvidas', 'longo', ['full' => 1]),
                'epis' => $f('Equipamentos de proteção individual', 'longo', ['full' => 1]),
                'medidas' => $f('Medidas preventivas', 'longo', ['full' => 1]),
                'obrigacoes' => $f('Obrigações', 'longo', ['full' => 1]),
                'sancoes' => $f('Sanções', 'longo', ['full' => 1]),
                'procedimentos' => $f('Procedimentos em caso de acidente', 'longo', ['full' => 1]),
                'normas' => $f('Normas internas', 'longo', ['full' => 1]),
                'obs' => $f('Observações', 'longo', ['full' => 1]),
                'termo' => $f('Termo de responsabilidade', 'longo', ['full' => 1]),
            ],
            'calc' => [],
        ],
        'equipamentos' => [
            'grupo' => 'Patrimônio e documentos', 'titulo' => 'Máquinas e equipamentos', 'singular' => 'equipamento', 'emp' => 'opc', 'ordem' => 'nome',
            'ajuda' => 'Lista de máquinas, equipamentos e ferramentas sob controle do SESMT.',
            'campos' => [
                'empresa' => $f('Empresa', 'empresa', ['l' => 1]),
                'nome' => $f('Máquina / equipamento / ferramenta', 'txt', ['r' => 1, 'l' => 1, 'q' => 1]),
                'modelo' => $f('Modelo', 'txt', ['l' => 1]),
                'fabricante' => $f('Fabricante', 'txt', ['l' => 1]),
                'ano' => $f('Ano', 'int'),
                'tipo' => $f('Tipo'),
                'potencia' => $f('Potência'),
                'voltagem' => $f('Voltagem'),
                'setor' => $f('Setor', 'lista:setor'),
            ],
            'calc' => [],
        ],
        'manutencoes' => [
            'grupo' => 'Patrimônio e documentos', 'titulo' => 'Manutenção de equipamentos', 'singular' => 'manutenção', 'emp' => 'nenhum', 'ordem' => 'data DESC',
            'ajuda' => 'Manutenções realizadas ou agendadas dos equipamentos.',
            'campos' => [
                'equipamento_id' => $f('Equipamento', 'ref:equipamentos', ['r' => 1, 'l' => 1]),
                'data' => $f('Data', 'data', ['r' => 1, 'l' => 1]),
                'status' => $f('Status', 'lista:manut_status', ['l' => 1]),
                'tipo' => $f('Tipo', 'lista:manut_tipo', ['l' => 1]),
                'prioridade' => $f('Prioridade', 'lista:manut_prioridade', ['l' => 1]),
                'itens' => $f('Itens analisados e/ou resolvidos', 'longo', ['full' => 1, 'q' => 1]),
                'custo' => $f('Custo (R$)', 'num', ['l' => 1]),
                'responsavel' => $f('Responsável', 'txt', ['q' => 1]),
            ],
            'calc' => [],
        ],
        'extintores' => [
            'grupo' => 'Patrimônio e documentos', 'titulo' => 'Extintores', 'singular' => 'extintor', 'emp' => 'nenhum', 'ordem' => 'localizacao',
            'ajuda' => 'Controle de recarga e teste hidrostático. O prazo do teste está em Configurações.',
            'campos' => [
                'tipo' => $f('Tipo do extintor (tipo + carga)', 'lista:extintor_tipo', ['r' => 1, 'l' => 1]),
                'inmetro' => $f('Nº Inmetro', 'txt', ['l' => 1, 'q' => 1]),
                'localizacao' => $f('Localização', 'txt', ['l' => 1, 'q' => 1]),
                'data_recarga' => $f('Data da recarga', 'data', ['l' => 1]),
                'validade_meses' => $f('Validade da recarga (em meses)', 'int'),
                'data_teste' => $f('Data do último teste hidrostático', 'data'),
                'obs' => $f('Observações', 'longo', ['full' => 1]),
            ],
            'calc' => ['proxima' => 'Próxima recarga', 'situacao' => 'Recarga', 'proximo_teste' => 'Próximo teste', 'situacao2' => 'Teste hidrostático'],
        ],
        'hidrantes' => [
            'grupo' => 'Patrimônio e documentos', 'titulo' => 'Hidrantes', 'singular' => 'hidrante', 'emp' => 'nenhum', 'ordem' => 'localizacao',
            'ajuda' => 'Inspeção dos hidrantes e prazo do teste hidrostático.',
            'campos' => [
                'localizacao' => $f('Localização', 'txt', ['r' => 1, 'l' => 1, 'q' => 1]),
                'abrigo' => $f('Abrigo', 'lista:sn'),
                'data_teste' => $f('Data do teste hidrostático', 'data', ['l' => 1]),
                'lacre' => $f('Lacre', 'lista:sn'),
                'mangueira' => $f('Mangueira', 'lista:sn'),
                'diametro' => $f('Diâmetro'),
                'comprimento' => $f('Comprimento (m)', 'num'),
                'esguicho' => $f('Esguicho', 'lista:sn'),
                'tampao' => $f('Tampão', 'lista:sn'),
                'chave' => $f('Chave', 'lista:sn'),
                'sinalizacao' => $f('Sinalização', 'lista:sn'),
                'obs' => $f('Observações', 'longo', ['full' => 1]),
            ],
            'calc' => ['proximo_teste' => 'Próximo teste', 'situacao' => 'Teste hidrostático'],
        ],
        'veiculos' => [
            'grupo' => 'Patrimônio e documentos', 'titulo' => 'Veículos da frota', 'singular' => 'veículo', 'emp' => 'opc', 'ordem' => 'placa',
            'ajuda' => 'Cadastro dos veículos. As manutenções ficam em Manutenção da frota.',
            'campos' => [
                'empresa' => $f('Empresa', 'empresa', ['l' => 1]),
                'placa' => $f('Placa', 'txt', ['r' => 1, 'l' => 1, 'q' => 1]),
                'veiculo' => $f('Veículo', 'txt', ['r' => 1, 'l' => 1, 'q' => 1]),
                'tipo' => $f('Tipo', 'lista:tipo_veiculo', ['l' => 1]),
            ],
            'calc' => [],
        ],
        'frota_manut' => [
            'grupo' => 'Patrimônio e documentos', 'titulo' => 'Manutenção da frota', 'singular' => 'manutenção', 'emp' => 'nenhum', 'ordem' => 'data DESC',
            'ajuda' => 'Manutenções dos veículos.',
            'campos' => [
                'veiculo_id' => $f('Veículo', 'ref:veiculos', ['r' => 1, 'l' => 1]),
                'data' => $f('Data', 'data', ['r' => 1, 'l' => 1]),
                'status' => $f('Status', 'lista:manut_status', ['l' => 1]),
                'km' => $f('KM atual', 'int', ['l' => 1]),
                'tipo' => $f('Tipo de manutenção', 'lista:frota_manut_tipo', ['l' => 1]),
                'descricao' => $f('Descrição do serviço', 'longo', ['full' => 1, 'q' => 1]),
                'valor' => $f('Valor (R$)', 'num', ['l' => 1]),
                'oficina' => $f('Empresa / oficina', 'txt', ['q' => 1]),
                'detalhes' => $f('Detalhes do serviço', 'longo', ['full' => 1]),
            ],
            'calc' => [],
        ],
        'quimicos' => [
            'grupo' => 'Patrimônio e documentos', 'titulo' => 'Produtos químicos', 'singular' => 'produto químico', 'emp' => 'nenhum', 'ordem' => 'nome_comercial',
            'ajuda' => 'Inventário de produtos químicos com FISPQ e classe de risco.',
            'campos' => [
                'nome_comercial' => $f('Nome comercial', 'txt', ['r' => 1, 'l' => 1, 'q' => 1]),
                'nome_tecnico' => $f('Nome técnico / substância química', 'txt', ['q' => 1]),
                'fabricante' => $f('Fabricante', 'txt', ['l' => 1]),
                'perigo' => $f('Representa perigo?', 'lista:quimico_perigo', ['l' => 1]),
                'classe' => $f('Classe de risco', 'txt', ['l' => 1]),
                'onu' => $f('Nº ONU'),
                'cas' => $f('Nº CAS'),
                'embalagem' => $f('Tipo da embalagem'),
                'material_embalagem' => $f('Material da embalagem'),
                'local' => $f('Local de armazenamento', 'txt', ['l' => 1]),
                'quantidade' => $f('Quantidade armazenada'),
                'aprovado' => $f('Aprovado?', 'lista:sn'),
                'orgao' => $f('Órgão fiscalizador'),
                'fornecedor' => $f('Fornecedor', 'txt', ['q' => 1]),
                'fispq' => $f('Possui FISPQ?', 'lista:sn', ['l' => 1]),
                'local_fispq' => $f('Local da FISPQ'),
                'pictogramas' => $f('Pictogramas (I, C, T, R, P)'),
                'controle' => $f('Controle interno'),
                'destinacao' => $f('Destinação do produto químico', 'txt', ['full' => 1]),
            ],
            'calc' => [],
        ],
        'documentos' => [
            'grupo' => 'Patrimônio e documentos', 'titulo' => 'Documentos', 'singular' => 'documento', 'emp' => 'opc', 'ordem' => 'nome',
            'ajuda' => 'Documentos do SESMT (PGR, PCMSO, laudos etc.) com controle de validade.',
            'campos' => [
                'empresa' => $f('Empresa', 'empresa', ['l' => 1]),
                'nome' => $f('Nome do documento', 'txt', ['r' => 1, 'l' => 1, 'q' => 1]),
                'tipo' => $f('Tipo', 'txt', ['l' => 1]),
                'area' => $f('Área', 'txt', ['l' => 1]),
                'data' => $f('Data', 'data', ['l' => 1]),
                'validade_meses' => $f('Validade (em meses)', 'int'),
                'controlar' => $f('Controlar validade?', 'lista:sn', ['pad' => 'Sim']),
                'revisao' => $f('Revisão'),
                'data_revisao' => $f('Data da última revisão', 'data'),
            ],
            'calc' => ['vencimento' => 'Vencimento', 'situacao' => 'Situação'],
        ],
    ];
    return $r;
}
